// GENERATED by scripts/gen-core.mjs — do not hand-edit. Re-run the script after
// changing src/data/manifest.json or the extracted collection data.

var PROXY = 'https://young-truth-052a.kiluconsta.workers.dev';
var PROXY_HOSTS = [
  'twimg.com', 'video.twimg.com', 'coomer.st', 'redgifs.com',
  'tumblr.com', 'lpsg.com', 'rule34.xxx', 'cartoonsworld.vip',
  'monstercockland.com', 'gayforfuns.com', 'gff.network',
  'dropbox.com', 'dropboxusercontent.com', 'googleusercontent.com',
  'bsky.network', 'video.bsky.app'
];

function proxyUrl(url) {
  if (!url || !PROXY) return url;
  url = normalizeDropbox(url);
  try {
    var host = new URL(url).hostname;
    var needsProxy = PROXY_HOSTS.some(function(h) { return host === h || host.endsWith('.' + h); });
    return needsProxy ? PROXY + '?url=' + encodeURIComponent(url) : url;
  } catch(e) { return url; }
}

function normalizeDropbox(url) {
  try {
    if (url.indexOf('dropbox.com') === -1) return url;
    var u = new URL(url);
    if (u.hostname === 'www.dropbox.com' || u.hostname === 'dropbox.com') u.hostname = 'dl.dropboxusercontent.com';
    u.searchParams.delete('dl');
    u.searchParams.set('raw', '1');
    return u.toString();
  } catch(e) { return url; }
}

function showHome() { window.location.href = '/'; }

var COLLECTION_META = {
  "bomb-ass-dee": {
    "label": "Bomb Ass Dee",
    "icon": "💣",
    "accent": "#ff2d55",
    "type": "video",
    "count": 636
  },
  "bomb-ass-dee-pt-2": {
    "label": "Bomb Ass Dee Pt.2",
    "icon": "💥",
    "accent": "#ff6b00",
    "type": "video",
    "count": 1113
  },
  "bluesky-likes": {
    "label": "BlueSky Likes",
    "icon": "🦋",
    "accent": "#0085ff",
    "type": "video",
    "count": 249
  },
  "coomer": {
    "label": "Coomer",
    "icon": "🍑",
    "accent": "#9b59b6",
    "type": "video",
    "count": 48
  },
  "sandf": {
    "label": "S&F",
    "icon": "🔥",
    "accent": "#00c97f",
    "type": "image",
    "count": 140
  },
  "images": {
    "label": "Images",
    "icon": "🖼️",
    "accent": "#e0b84a",
    "type": "image",
    "count": 234
  },
  "x-likes-long": {
    "label": "X Likes (Long)",
    "icon": "𝕏",
    "accent": "#3d9be0",
    "type": "video",
    "count": 584
  },
  "meatsenpaii": {
    "label": "MeatSenpaii",
    "icon": "🥩",
    "accent": "#ff4757",
    "type": "video",
    "count": 12
  },
  "x-likes-short": {
    "label": "X Likes (Short)",
    "icon": "⚡",
    "accent": "#22c9d6",
    "type": "video",
    "count": 299
  },
  "tumblr": {
    "label": "Tumblr",
    "icon": "📐",
    "accent": "#e0708a",
    "type": "image",
    "count": 819
  },
  "show-off": {
    "label": "Show Off",
    "icon": "✨",
    "accent": "#d8a53c",
    "type": "image",
    "count": 221
  },
  "gifs": {
    "label": "GIFs",
    "icon": "🟢",
    "accent": "#7bc26f",
    "type": "image",
    "count": 461
  },
  "animations": {
    "label": "Animations",
    "icon": "🦹🏾‍♂️",
    "accent": "#a94ee0",
    "type": "video",
    "count": 71
  },
  "dropbox": {
    "label": "Dropbox",
    "icon": "📥",
    "accent": "#9096a0",
    "type": "video",
    "count": 1910
  }
};

var Favourites = (function() {
  var KEY = 'vault-favourites';
  var _list = null, _set = null;

  function load() {
    if (_list) return _list;
    try { _list = JSON.parse(localStorage.getItem(KEY) || '[]'); } catch(e) { _list = []; }
    if (!Array.isArray(_list)) _list = [];
    return _list;
  }
  function rebuildSet() { _set = new Set(load().map(function(x){ return x.url; })); }
  function getSet() { if (!_set) rebuildSet(); return _set; }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(_list)); } catch(e) {}
    rebuildSet();
  }
  function has(url) { return getSet().has(url); }
  function list() { return load().slice(); }
  function count() { return load().length; }

  function toggle(entry) {
    var l = load(), i = -1;
    for (var k = 0; k < l.length; k++) { if (l[k].url === entry.url) { i = k; break; } }
    var state;
    if (i >= 0) { l.splice(i, 1); state = false; }
    else { l.unshift({ url: entry.url, slug: entry.slug, type: entry.type, start: entry.start || null, end: entry.end || null, t: Date.now() }); state = true; }
    save();
    document.dispatchEvent(new CustomEvent('vault-fav-change', { detail: { url: entry.url, state: state } }));
    return state;
  }

  // Wholesale replacement from sync — silent so it never re-triggers a push
  function _replaceAll(newList) {
    _list = Array.isArray(newList) ? newList.slice() : [];
    save();
    document.dispatchEvent(new CustomEvent('vault-fav-change', { detail: { url: null, state: null, silent: true } }));
  }

  window.addEventListener('storage', function(e) {
    if (e.key !== KEY) return;
    _list = null; _set = null;
    document.dispatchEvent(new CustomEvent('vault-fav-change', { detail: { url: null, state: null } }));
  });

  var HEART_SVG = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>';

  function makeHeart(getEntry, opts) {
    opts = opts || {};
    var btn = document.createElement('button');
    btn.type = 'button'; btn.className = 'fav-heart';
    btn.setAttribute('aria-label', 'Toggle favourite');
    btn.innerHTML = HEART_SVG;

    function refresh() {
      var e = getEntry();
      var on = !!(e && e.url && has(e.url));
      btn.classList.toggle('is-fav', on);
      btn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }
    btn.addEventListener('click', function(ev) {
      ev.stopPropagation(); ev.preventDefault();
      var e = getEntry();
      if (!e || !e.url) return;
      toggle(e); refresh();
      btn.classList.remove('just-toggled');
      void btn.offsetWidth;
      btn.classList.add('just-toggled');
      if (typeof opts.onToggle === 'function') opts.onToggle(e);
    });
    document.addEventListener('vault-fav-change', function(ev) {
      var e = getEntry();
      if (!e || !e.url) { refresh(); return; }
      if (!ev.detail || ev.detail.url === null || ev.detail.url === e.url) refresh();
    });
    btn.__refresh = refresh;
    refresh();
    return btn;
  }

  function initSection(sec, opts) {
    opts = opts || {};
    var slug = (location.pathname.split('/').filter(Boolean).pop() || '').replace(/\.html$/, '');
    var type = opts.type || 'video';
    sec.querySelectorAll('[data-fav-url]').forEach(function(tile) {
      if (tile.__favDone) return;
      tile.__favDone = true;
      var url = tile.getAttribute('data-fav-url');
      var start = tile.getAttribute('data-fav-start');
      var end = tile.getAttribute('data-fav-end');
      tile.appendChild(makeHeart(function() {
        return { url: url, slug: slug, type: type, start: start ? Number(start) : null, end: end ? Number(end) : null };
      }, { variant: 'tile' }));
    });
    var api = { setCurrent: function() {} };
    var bar = opts.platterEl;
    if (bar) {
      var curEntry = null;
      var heart = makeHeart(function() { return curEntry; }, { variant: 'inline' });
      if (bar.classList.contains('vs-lb-platter')) {
        var sep = document.createElement('div'); sep.className = 'platter-sep'; bar.appendChild(sep);
      }
      bar.appendChild(heart);
      api.setCurrent = function(entry) { curEntry = entry; if (heart.__refresh) heart.__refresh(); };
    }
    return api;
  }

  return { has: has, list: list, count: count, toggle: toggle, makeHeart: makeHeart, initSection: initSection, META: COLLECTION_META, _replaceAll: _replaceAll };
})();

// ── Poster capture: IndexedDB cache + bounded capture queue ──
// Cache reads run in parallel (cheap); only cache MISSES enter the capture
// queue, which decodes at most CONCURRENCY videos at a time. Without this,
// scrolling a large page spawns dozens of simultaneous video decoders.
var VaultPosters = (function () {
  var DB_NAME = 'vault-posters', STORE = 'posters';
  var _db = null, _dbFail = false;
  var CONCURRENCY = 2, TIMEOUT_MS = 15000;

  function db() {
    return new Promise(function (res) {
      if (_db) return res(_db);
      if (_dbFail || !window.indexedDB) return res(null);
      var req = indexedDB.open(DB_NAME, 1);
      req.onupgradeneeded = function () { req.result.createObjectStore(STORE); };
      req.onsuccess = function () { _db = req.result; res(_db); };
      req.onerror = function () { _dbFail = true; res(null); };
    });
  }
  function idbGet(key) {
    return db().then(function (d) {
      if (!d) return null;
      return new Promise(function (res) {
        try {
          var rq = d.transaction(STORE, 'readonly').objectStore(STORE).get(key);
          rq.onsuccess = function () { res(rq.result || null); };
          rq.onerror = function () { res(null); };
        } catch (e) { res(null); }
      });
    });
  }
  function idbSet(key, val) {
    db().then(function (d) {
      if (!d) return;
      try { d.transaction(STORE, 'readwrite').objectStore(STORE).put(val, key); } catch (e) {}
    });
  }

  var queue = [], active = 0;
  function pump() {
    while (active < CONCURRENCY && queue.length) { active++; runCapture(queue.shift()); }
  }
  function runCapture(job) {
    var v = document.createElement('video');
    v.muted = true; v.playsInline = true; v.preload = 'metadata'; v.crossOrigin = 'anonymous';
    v.style.cssText = 'position:absolute;width:1px;height:1px;opacity:0;pointer-events:none';
    var done = false, timer = null;
    function finish(dataUrl) {
      if (done) return;
      done = true;
      clearTimeout(timer);
      if (v.__hls) { try { v.__hls.destroy(); } catch (e) {} v.__hls = null; }
      v.removeAttribute('src'); try { v.load(); } catch (e) {} v.remove();
      active--; pump();
      if (dataUrl) idbSet(job.key, dataUrl);
      job.cb(dataUrl || null);
    }
    timer = setTimeout(function () { finish(null); }, TIMEOUT_MS);
    v.addEventListener('loadedmetadata', function () {
      var t = job.time;
      if (v.duration && isFinite(v.duration)) t = Math.min(t, Math.max(0, v.duration - 0.1));
      try { v.currentTime = t; } catch (e) {}
    });
    function snap() {
      try {
        var c = document.createElement('canvas');
        c.width = 240;
        c.height = Math.round(240 * (v.videoHeight / v.videoWidth || 1.33));
        c.getContext('2d').drawImage(v, 0, 0, c.width, c.height);
        finish(c.toDataURL('image/jpeg', 0.72));
      } catch (e) { finish(null); }
    }
    v.addEventListener('seeked', snap);
    v.addEventListener('error', function () { finish(null); });
    document.body.appendChild(v);
    var url = job.src;
    var isHls = /\.m3u8(\?|$)/i.test(url);
    if (isHls && !v.canPlayType('application/vnd.apple.mpegurl') && window.Hls && window.Hls.isSupported()) {
      var h = new window.Hls({ maxBufferLength: 5 });
      h.on(window.Hls.Events.ERROR, function (ev, d) { if (d.fatal) finish(null); });
      h.loadSource(url); h.attachMedia(v); v.__hls = h;
    } else {
      v.src = url;
    }
  }

  // Pre-generated thumbs: /thumbs/<sha1-16 of url@time>.jpg, produced by the
  // GitHub Action (tools/generate-thumbs.mjs). Hash MUST match that script.
  // A manifest (thumbs/index.json) is fetched ONCE and consulted locally, so
  // we never request a thumb that doesn't exist — no 404 noise.
  var _manifest = null; // Promise<Set|null>
  function manifest() {
    if (_manifest) return _manifest;
    if (typeof window.fetch !== 'function') { _manifest = Promise.resolve(null); return _manifest; }
    _manifest = fetch('/thumbs/index.json').then(function (r) {
      if (!r.ok) return null;
      return r.json().then(function (arr) { return new Set(arr); });
    }).catch(function () { return null; });
    return _manifest;
  }
  function thumbHash(url, time) {
    if (!window.crypto || !crypto.subtle || !window.TextEncoder) return Promise.resolve(null);
    var bytes = new TextEncoder().encode(url + '@' + time);
    return crypto.subtle.digest('SHA-1', bytes).then(function (buf) {
      var hex = '';
      var arr = new Uint8Array(buf);
      for (var i = 0; i < 8; i++) hex += (arr[i] < 16 ? '0' : '') + arr[i].toString(16);
      return hex;
    }).catch(function () { return null; });
  }
  function tryStaticThumb(url, time) {
    return manifest().then(function (set) {
      if (!set || !set.size) return null;
      return thumbHash(url, time).then(function (hash) {
        return (hash && set.has(hash)) ? ('/thumbs/' + hash + '.jpg') : null;
      });
    });
  }

  // load(rawUrl, timeSecs, cb): cb(srcString|null).
  // Order: pre-generated file (free) → IDB cache → live capture queue.
  function load(rawUrl, time, cb) {
    tryStaticThumb(rawUrl, time).then(function (staticSrc) {
      if (staticSrc) { cb(staticSrc); return; }
      var key = rawUrl + '@' + time;
      idbGet(key).then(function (hit) {
        if (hit) { cb(hit); return; }
        queue.push({ key: key, src: proxyUrl(rawUrl), time: time, cb: cb });
        pump();
      });
    });
  }
  return { load: load };
})();

// ── Favourites sync via private GitHub Gist ────────────────
// Token (classic PAT, "gist" scope ONLY) lives in localStorage. The gist is
// found by filename or created on first enable. Pull-on-boot: newer side wins
// wholesale. Pushes are debounced so rapid toggles = one API call.
var VaultSync = (function () {
  var API = 'https://api.github.com';
  var FILENAME = 'vault-favourites.json';
  var T_KEY = 'vault-sync-token', G_KEY = 'vault-sync-gist', U_KEY = 'vault-favourites-updated';
  var pushTimer = null, status = 'off';

  function token() { try { return localStorage.getItem(T_KEY) || ''; } catch (e) { return ''; } }
  function gistId() { try { return localStorage.getItem(G_KEY) || ''; } catch (e) { return ''; } }
  function localUpdated() { try { return Number(localStorage.getItem(U_KEY)) || 0; } catch (e) { return 0; } }
  function markUpdated(t) { try { localStorage.setItem(U_KEY, String(t)); } catch (e) {} }
  function enabled() { return !!token(); }

  function setStatus(s, detail) {
    status = s;
    document.dispatchEvent(new CustomEvent('vault-sync-status', { detail: { status: s, detail: detail || '' } }));
  }
  function gh(path, opts) {
    opts = opts || {};
    opts.headers = Object.assign({
      'Authorization': 'Bearer ' + token(),
      'Accept': 'application/vnd.github+json'
    }, opts.headers || {});
    return fetch(API + path, opts);
  }

  function findOrCreateGist() {
    if (gistId()) return Promise.resolve(gistId());
    return gh('/gists?per_page=100').then(function (r) {
      if (!r.ok) throw new Error('token rejected (' + r.status + ')');
      return r.json();
    }).then(function (gists) {
      var hit = gists.find(function (g) { return g.files && g.files[FILENAME]; });
      if (hit) { localStorage.setItem(G_KEY, hit.id); return hit.id; }
      var files = {};
      files[FILENAME] = { content: JSON.stringify({ updated: 0, list: [] }) };
      return gh('/gists', {
        method: 'POST',
        body: JSON.stringify({ description: 'The Vault — favourites sync', public: false, files: files })
      }).then(function (r) {
        if (!r.ok) throw new Error('gist create failed (' + r.status + ')');
        return r.json();
      }).then(function (g) { localStorage.setItem(G_KEY, g.id); return g.id; });
    });
  }

  function pull() {
    if (!enabled()) return Promise.resolve(false);
    setStatus('syncing');
    return findOrCreateGist().then(function (id) {
      return gh('/gists/' + id).then(function (r) {
        if (!r.ok) throw new Error('gist fetch failed (' + r.status + ')');
        return r.json();
      });
    }).then(function (g) {
      var file = g.files && g.files[FILENAME];
      var doc = { updated: 0, list: [] };
      try { doc = JSON.parse(file.content); } catch (e) {}
      if ((doc.updated || 0) > localUpdated() && Array.isArray(doc.list)) {
        Favourites._replaceAll(doc.list);
        markUpdated(doc.updated);
        setStatus('synced');
        return true;
      }
      setStatus('synced');
      return false;
    }).catch(function (e) { setStatus('error', String(e.message || e)); return false; });
  }

  function pushSoon() {
    if (!enabled()) return;
    if (pushTimer) clearTimeout(pushTimer);
    setStatus('pending');
    pushTimer = setTimeout(pushNow, 2500);
  }
  function pushNow() {
    if (!enabled()) return Promise.resolve();
    var now = Date.now();
    markUpdated(now);
    setStatus('syncing');
    return findOrCreateGist().then(function (id) {
      var files = {};
      files[FILENAME] = { content: JSON.stringify({ updated: now, list: Favourites.list() }) };
      return gh('/gists/' + id, { method: 'PATCH', body: JSON.stringify({ files: files }) });
    }).then(function (r) {
      if (!r.ok) throw new Error('push failed (' + r.status + ')');
      setStatus('synced');
    }).catch(function (e) { setStatus('error', String(e.message || e)); });
  }

  function enable(tok) {
    try { localStorage.setItem(T_KEY, tok.trim()); } catch (e) {}
    return pull().then(function () { if (status !== 'error') pushNow(); return status !== 'error'; });
  }
  function disable() {
    try { localStorage.removeItem(T_KEY); localStorage.removeItem(G_KEY); } catch (e) {}
    if (pushTimer) clearTimeout(pushTimer);
    setStatus('off');
  }

  // Local favourite changes → schedule a push (remote-applied changes carry silent=true)
  document.addEventListener('vault-fav-change', function (ev) {
    if (ev.detail && ev.detail.silent) return;
    if (ev.detail && ev.detail.url === null) return; // cross-tab storage echo
    pushSoon();
  });
  // Flush pending push if the tab closes quickly after a toggle
  document.addEventListener('visibilitychange', function () {
    if (document.hidden && status === 'pending') pushNow();
  });
  if (enabled()) setTimeout(pull, 0);

  return { enabled: enabled, enable: enable, disable: disable, pull: pull,
           getStatus: function () { return status; } };
})();

// ── Shared lightbox / page UX helpers ─────────────────────
var VaultLB = {
  // Scroll lock while a lightbox is open
  lock: function (on) { document.body.classList.toggle('lb-open', !!on); },
  // Spinner state on a wrap element (adds/removes .lb-loading)
  loading: function (el, on) { if (el) el.classList.toggle('lb-loading', !!on); },
  // Horizontal swipe → onPrev/onNext. Vertical scrolling untouched.
  swipe: function (el, onPrev, onNext) {
    var x0 = null, y0 = null;
    el.addEventListener('touchstart', function (e) {
      if (e.touches.length !== 1) { x0 = null; return; }
      x0 = e.touches[0].clientX; y0 = e.touches[0].clientY;
    }, { passive: true });
    el.addEventListener('touchend', function (e) {
      if (x0 === null) return;
      var dx = e.changedTouches[0].clientX - x0;
      var dy = e.changedTouches[0].clientY - y0;
      x0 = null;
      if (Math.abs(dx) < 48 || Math.abs(dx) < Math.abs(dy) * 1.2) return;
      if (dx > 0) onPrev(); else onNext();
    }, { passive: true });
  },
  // Persist lightbox mode toggles (shuffle/loop/auto/timer) across pages
  getMode: function (name) {
    try { return sessionStorage.getItem('vault-lb-' + name) === '1'; } catch (e) { return false; }
  },
  setMode: function (name, on) {
    try {
      if (on) sessionStorage.setItem('vault-lb-' + name, '1');
      else sessionStorage.removeItem('vault-lb-' + name);
    } catch (e) {}
  },
  // Scroll-to-top pill: shows after a screen of scrolling
  initScrollTop: function () {
    var btn = document.querySelector('.scroll-top');
    if (!btn) return;
    var ticking = false;
    function update() {
      btn.classList.toggle('show', window.scrollY > window.innerHeight);
      ticking = false;
    }
    window.addEventListener('scroll', function () {
      if (!ticking) { ticking = true; requestAnimationFrame(update); }
    }, { passive: true });
    btn.addEventListener('click', function () { window.scrollTo({ top: 0, behavior: 'smooth' }); });
    update();
  },
  // Jump-nav dots for pages with section dividers (desktop)
  initJumpNav: function (dividerEls) {
    var nav = document.querySelector('.vs-jump-nav');
    if (!nav || !dividerEls || dividerEls.length < 2) return;
    dividerEls.forEach(function (d) {
      var pill = document.createElement('button');
      pill.className = 'vs-jump-pill';
      pill.type = 'button';
      pill.title = d.textContent;
      pill.setAttribute('aria-label', 'Jump to ' + d.textContent);
      pill.addEventListener('click', function () {
        d.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });
      nav.appendChild(pill);
    });
    var obs = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (!en.isIntersecting) return;
        var idx = dividerEls.indexOf(en.target);
        nav.querySelectorAll('.vs-jump-pill').forEach(function (p, i) {
          p.classList.toggle('active', i === idx);
        });
      });
    }, { rootMargin: '-10% 0px -70% 0px' });
    dividerEls.forEach(function (d) { obs.observe(d); });
  }
};

(function() {
  function applyIdle() { document.documentElement.classList.toggle('power-idle', document.hidden); }
  document.addEventListener('visibilitychange', applyIdle);
  applyIdle();
})();
