// GENERATED by scripts/gen-core.mjs — do not hand-edit. Re-run the script after
// changing src/data/manifest.json or the extracted collection data.

var PROXY = 'https://young-truth-052a.kiluconsta.workers.dev';
var PROXY_HOSTS = [
  'twimg.com', 'video.twimg.com', 'coomer.st', 'redgifs.com',
  'tumblr.com', 'lpsg.com', 'rule34.xxx', 'cartoonsworld.vip',
  'monstercockland.com', 'gayforfuns.com', 'gff.network',
  'dropbox.com', 'dropboxusercontent.com', 'googleusercontent.com',
  'bsky.network', 'video.bsky.app'
];

function proxyUrl(url) {
  if (!url || !PROXY) return url;
  url = normalizeDropbox(url);
  try {
    var host = new URL(url).hostname;
    var needsProxy = PROXY_HOSTS.some(function(h) { return host === h || host.endsWith('.' + h); });
    return needsProxy ? PROXY + '?url=' + encodeURIComponent(url) : url;
  } catch(e) { return url; }
}

function normalizeDropbox(url) {
  try {
    if (url.indexOf('dropbox.com') === -1) return url;
    var u = new URL(url);
    if (u.hostname === 'www.dropbox.com' || u.hostname === 'dropbox.com') u.hostname = 'dl.dropboxusercontent.com';
    u.searchParams.delete('dl');
    u.searchParams.set('raw', '1');
    return u.toString();
  } catch(e) { return url; }
}

function showHome() { window.location.href = '/'; }

var COLLECTION_META = {
  "bomb-ass-dee": {
    "label": "Bomb Ass Dee",
    "accent": "#ff2d55",
    "type": "video",
    "count": 636
  },
  "bomb-ass-dee-pt-2": {
    "label": "Bomb Ass Dee Pt.2",
    "accent": "#ff6b00",
    "type": "video",
    "count": 1113
  },
  "bluesky-likes": {
    "label": "BlueSky Likes",
    "accent": "#0085ff",
    "type": "video",
    "count": 249
  },
  "coomer": {
    "label": "Coomer",
    "accent": "#9b59b6",
    "type": "video",
    "count": 48
  },
  "sandf": {
    "label": "S&F",
    "accent": "#00c97f",
    "type": "image",
    "count": 140
  },
  "images": {
    "label": "Images",
    "accent": "#e0b84a",
    "type": "image",
    "count": 234
  },
  "x-likes-long": {
    "label": "X Likes (Long)",
    "accent": "#3d9be0",
    "type": "video",
    "count": 548
  },
  "meatsenpaii": {
    "label": "MeatSenpaii",
    "accent": "#ff4757",
    "type": "video",
    "count": 12
  },
  "x-likes-short": {
    "label": "X Likes (Short)",
    "accent": "#22c9d6",
    "type": "video",
    "count": 299
  },
  "tumblr": {
    "label": "Tumblr",
    "accent": "#e0708a",
    "type": "image",
    "count": 819
  },
  "show-off": {
    "label": "Show Off",
    "accent": "#d8a53c",
    "type": "image",
    "count": 221
  },
  "gifs": {
    "label": "GIFs",
    "accent": "#7bc26f",
    "type": "image",
    "count": 461
  },
  "animations": {
    "label": "Animations",
    "accent": "#a94ee0",
    "type": "video",
    "count": 71
  },
  "dropbox": {
    "label": "Dropbox",
    "accent": "#9096a0",
    "type": "video",
    "count": 1910
  }
};

var Favourites = (function() {
  var KEY = 'vault-favourites';
  var _list = null, _set = null;

  function load() {
    if (_list) return _list;
    try { _list = JSON.parse(localStorage.getItem(KEY) || '[]'); } catch(e) { _list = []; }
    if (!Array.isArray(_list)) _list = [];
    return _list;
  }
  function rebuildSet() { _set = new Set(load().map(function(x){ return x.url; })); }
  function getSet() { if (!_set) rebuildSet(); return _set; }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(_list)); } catch(e) {}
    rebuildSet();
  }
  function has(url) { return getSet().has(url); }
  function list() { return load().slice(); }
  function count() { return load().length; }

  function toggle(entry) {
    var l = load(), i = -1;
    for (var k = 0; k < l.length; k++) { if (l[k].url === entry.url) { i = k; break; } }
    var state;
    if (i >= 0) { l.splice(i, 1); state = false; }
    else { l.unshift({ url: entry.url, slug: entry.slug, type: entry.type, start: entry.start || null, end: entry.end || null, t: Date.now() }); state = true; }
    save();
    document.dispatchEvent(new CustomEvent('vault-fav-change', { detail: { url: entry.url, state: state } }));
    return state;
  }

  window.addEventListener('storage', function(e) {
    if (e.key !== KEY) return;
    _list = null; _set = null;
    document.dispatchEvent(new CustomEvent('vault-fav-change', { detail: { url: null, state: null } }));
  });

  var HEART_SVG = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>';

  function makeHeart(getEntry, opts) {
    opts = opts || {};
    var btn = document.createElement('button');
    btn.type = 'button'; btn.className = 'fav-heart';
    btn.setAttribute('aria-label', 'Toggle favourite');
    btn.innerHTML = HEART_SVG;

    function refresh() {
      var e = getEntry();
      var on = !!(e && e.url && has(e.url));
      btn.classList.toggle('is-fav', on);
      btn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }
    btn.addEventListener('click', function(ev) {
      ev.stopPropagation(); ev.preventDefault();
      var e = getEntry();
      if (!e || !e.url) return;
      toggle(e); refresh();
      btn.classList.remove('just-toggled');
      void btn.offsetWidth;
      btn.classList.add('just-toggled');
      if (typeof opts.onToggle === 'function') opts.onToggle(e);
    });
    document.addEventListener('vault-fav-change', function(ev) {
      var e = getEntry();
      if (!e || !e.url) { refresh(); return; }
      if (!ev.detail || ev.detail.url === null || ev.detail.url === e.url) refresh();
    });
    btn.__refresh = refresh;
    refresh();
    return btn;
  }

  function initSection(sec, opts) {
    opts = opts || {};
    var slug = (location.pathname.split('/').filter(Boolean).pop() || '').replace(/\.html$/, '');
    var type = opts.type || 'video';
    sec.querySelectorAll('[data-fav-url]').forEach(function(tile) {
      if (tile.__favDone) return;
      tile.__favDone = true;
      var url = tile.getAttribute('data-fav-url');
      var start = tile.getAttribute('data-fav-start');
      var end = tile.getAttribute('data-fav-end');
      tile.appendChild(makeHeart(function() {
        return { url: url, slug: slug, type: type, start: start ? Number(start) : null, end: end ? Number(end) : null };
      }, { variant: 'tile' }));
    });
    var api = { setCurrent: function() {} };
    var bar = opts.platterEl;
    if (bar) {
      var curEntry = null;
      var heart = makeHeart(function() { return curEntry; }, { variant: 'inline' });
      if (bar.classList.contains('vs-lb-platter')) {
        var sep = document.createElement('div'); sep.className = 'platter-sep'; bar.appendChild(sep);
      }
      bar.appendChild(heart);
      api.setCurrent = function(entry) { curEntry = entry; if (heart.__refresh) heart.__refresh(); };
    }
    return api;
  }

  return { has: has, list: list, count: count, toggle: toggle, makeHeart: makeHeart, initSection: initSection, META: COLLECTION_META };
})();

(function() {
  function applyIdle() { document.documentElement.classList.toggle('power-idle', document.hidden); }
  document.addEventListener('visibilitychange', applyIdle);
  applyIdle();
})();
